# ex. for the collision check benchmark
aggregate_config:
  statistics:
    - raw_metric: time
      new_metric: collision_check
      type: frequency
    - raw_metric: collision
      new_metric: avg_collision
      type: average
    - raw_metric: contact_count
      new_metric: avg_contact_count
      type: average
