<?xml version="1.0" ?>
<robot name="scene" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find scene_parser)/config/utils.xacro" />
  <xacro:include filename="$(find scene_parser)/config/opencrate.urdf.xacro" />
  <!-- Used to get bb information from real meshes -->
  <xacro:include filename="$(find moveit_benchmark_suite_resources)/objects/geometry.xacro" />

  <link name="world" />

  <xacro:framebox name="boxlid"
                  frame_id="world"
                  dimensions="${boxlid['bby']} ${boxlid['bbz']} ${boxlid['bbx']}"
                  xyz="${0.16 + boxlid['bby']/2} 0 0"/>
    
  <xacro:opencrate name="clearbox1"
                   frame_id="world"
                   xyz="${0.16 + clearbox['bby']/2} ${-(clearbox['bbx']/2 + boxlid['bbz']/2)} 0" rpy="0 0 0"
                   dimensions="${clearbox['bby']} ${clearbox['bbx']} ${clearbox['bbz']}"
                   thickness="0.00709"/>

  <xacro:opencrate name="clearbox2"
                   frame_id="clearbox1"
                   xyz="0 ${clearbox['bbx'] + boxlid['bbz']} 0" rpy="0 0 0"
                   dimensions="${clearbox['bby']} ${clearbox['bbx']} ${clearbox['bbz']}"
                   thickness="0.00709"/>

  <xacro:macro name="linearpattern" params="current:=0 frame_id:=^ index:=0 max:=^ xyz:=^ rpy=^|'0 0 0' gap:=^">

    <xacro:if value="${max > current}">
      <xacro:framebox name="woodblock${index+current}"
                      frame_id="${frame_id}"
                      dimensions="${woodblock['bbx']} ${woodblock['bby']} ${woodblock['bbz']}"
                      xyz="${float(xyz.split()[0]) + current*float(gap.split()[0])}
                           ${float(xyz.split()[1]) + current*float(gap.split()[1])}
                           ${float(xyz.split()[2]) + current*float(gap.split()[2])}" />
      <xacro:linearpattern current="${current+1}" index="${index}"/>
    </xacro:if>
  </xacro:macro>

  <xacro:linearpattern index="1"  max="4"  frame_id="clearbox1"  gap="0 ${woodblock['bby']*2} 0" xyz="${3*woodblock['bbx']} ${(-3*woodblock['bbx'])} 0" rpy="0 0 0"/>
  <xacro:linearpattern index="5"  max="4"  frame_id="woodblock1/bottom" gap="0 ${woodblock['bby']*2} 0" xyz="${-2*woodblock['bbx']} 0 0"/>
  <xacro:linearpattern index="9"  max="4"  frame_id="woodblock5/bottom" gap="0 ${woodblock['bby']*2} 0" xyz="${-2*woodblock['bbx']} 0 0"/>
  <xacro:linearpattern index="13" max="4"  frame_id="woodblock9/bottom" gap="0 ${woodblock['bby']*2} 0" xyz="${-2*woodblock['bbx']} 0 0"/>

</robot>
