######################################
# Motion Planning (PlanningPipeline) #
######################################

# Describes benchmark parameters (independent of profilers)
benchmark_config:
  parameters:
    runs: 20                        # Number of trials for each query
    name: "MotionPlanning PP"       # Default ""    | Overridden by ROS Param /benchmark/name
    visualize: false                # Default false | Overridden by ROS Param /benchmark/visualize
    output_file: ""                 # Default ""    | Overridden by ROS Param /benchmark/output_file

# Evaluate pose goals on every 16 wood blocks for the bbt scenes using the panda robot in a start state.
profiler_config:

  # Override 'requests' with moveit_msgs/MotionPlanRequest respective field/s
  requests_override:
    allowed_planning_time: 10.0
    num_planning_attempts: 1

  # Resource moveit_msgs/MotionPlanRequest
  requests:
    - name: jc
      resource: package://moveit_benchmark_suite_resources/requests/bbt/panda/jc.yaml
    - name: poc-blk01
      resource: package://moveit_benchmark_suite_resources/requests/bbt/panda/poc_blk01.yaml
    - name: poc-blk02
      resource: package://moveit_benchmark_suite_resources/requests/bbt/panda/poc_blk02.yaml
    - name: poc-blk03
      resource: package://moveit_benchmark_suite_resources/requests/bbt/panda/poc_blk03.yaml
    - name: poc-blk04
      resource: package://moveit_benchmark_suite_resources/requests/bbt/panda/poc_blk04.yaml
    - name: poc-blk05
      resource: package://moveit_benchmark_suite_resources/requests/bbt/panda/poc_blk05.yaml
    - name: poc-blk06
      resource: package://moveit_benchmark_suite_resources/requests/bbt/panda/poc_blk06.yaml
    - name: poc-blk07
      resource: package://moveit_benchmark_suite_resources/requests/bbt/panda/poc_blk07.yaml
    - name: poc-blk08
      resource: package://moveit_benchmark_suite_resources/requests/bbt/panda/poc_blk08.yaml
    - name: poc-blk09
      resource: package://moveit_benchmark_suite_resources/requests/bbt/panda/poc_blk09.yaml
    - name: poc-blk10
      resource: package://moveit_benchmark_suite_resources/requests/bbt/panda/poc_blk10.yaml
    - name: poc-blk11
      resource: package://moveit_benchmark_suite_resources/requests/bbt/panda/poc_blk11.yaml
    - name: poc-blk12
      resource: package://moveit_benchmark_suite_resources/requests/bbt/panda/poc_blk12.yaml
    - name: poc-blk13
      resource: package://moveit_benchmark_suite_resources/requests/bbt/panda/poc_blk13.yaml
    - name: poc-blk14
      resource: package://moveit_benchmark_suite_resources/requests/bbt/panda/poc_blk14.yaml
    - name: poc-blk15
      resource: package://moveit_benchmark_suite_resources/requests/bbt/panda/poc_blk15.yaml
    - name: poc-blk16
      resource: package://moveit_benchmark_suite_resources/requests/bbt/panda/poc_blk16.yaml

  # Resource moveit_config (robot)
  robot:
    name: panda
    resources:
      urdf: package://moveit_benchmark_suite_resources/robots/panda/urdf/panda.urdf
      srdf: package://moveit_benchmark_suite_resources/robots/panda/config/panda.srdf
      kinematics: package://moveit_benchmark_suite_resources/robots/panda/config/kinematics.yaml
      joint_limits: package://moveit_benchmark_suite_resources/robots/panda/config/joint_limits.yaml

  # Resource moveit_msgs/PlanningScene
  scenes:
    - name: empty
      resource: package://moveit_benchmark_suite_resources/scenes/empty/empty.urdf.xacro
    - name: primitive
      resource: package://moveit_benchmark_suite_resources/scenes/bbt/panda/primitive.urdf.xacro
    - name: mesh_primitive_blender
      resource: package://moveit_benchmark_suite_resources/scenes/bbt/panda/mesh_box_blender.urdf.xacro
    - name: mesh_primitive_sw
      resource: package://moveit_benchmark_suite_resources/scenes/bbt/panda/mesh_box_solidworks.urdf.xacro
    # - name: mesh
    #   resource: package://moveit_benchmark_suite_resources/scenes/bbt/panda/mesh_16k.urdf.xacro

  collision_detectors:
    - FCL
    - Bullet

  # Resource moveit_config (planning pipeline)
  # - Override the 'requests' pipeline_id field
  # - Extends query 'planners' which overrides the 'requests' planner_id field
  planning_pipelines:
    - name: ompl
      resource: package://moveit_benchmark_suite_resources/robots/panda/config/ompl_planning.yaml
      parameters:
        planners:
          - RRT
          - RRTConnect
          - EST
          - PRM
          - LBKPIECE
          - BiEST
    # - name: chomp
    #   resource: package://moveit_benchmark_suite_resources/robots/panda/config/chomp_planning.yaml
    #   parameters:
    #     planners:
    #       - CHOMP
