######################################
# Motion Planning (PlanningPipeline) #
######################################

# Describes benchmark parameters (independent of profilers)
benchmark_config:
  parameters:
    runs: 20                        # Number of trials for each query
    name: "MotionPlanning PP"       # Default ""    | Overridden by ROS Param /benchmark/name
    visualize: false                # Default false | Overridden by ROS Param /benchmark/visualize
    output_file: ""                 # Default ""    | Overridden by ROS Param /benchmark/output_file

# Describes config for building motion planning pair-wise queries
profiler_config:

  # Override 'requests' with moveit_msgs/MotionPlanRequest respective field/s
  requests_override:
    allowed_planning_time: 10.0
    num_planning_attempts: 1

  # Resource moveit_msgs/MotionPlanRequest
  requests:
    - name: jc
      resource: package://moveit_benchmark_suite_resources/requests/bbt/panda/jc.yaml
    # - name: jc_pcp
    #   resource: package://moveit_benchmark_suite_resources/requests/bbt/panda/jc_pcp.yaml

  # Resource moveit_config (robot)
  robot:
    name: panda
    resources:
      urdf: package://moveit_benchmark_suite_resources/robots/panda/urdf/panda.urdf
      srdf: package://moveit_benchmark_suite_resources/robots/panda/config/panda.srdf
      kinematics: package://moveit_benchmark_suite_resources/robots/panda/config/kinematics.yaml
      joint_limits: package://moveit_benchmark_suite_resources/robots/panda/config/joint_limits.yaml

  # Resource moveit_msgs/PlanningScene
  scenes:
    - name: empty
      resource: package://moveit_benchmark_suite_resources/scenes/empty/empty.urdf.xacro
    - name: primitive
      resource: package://moveit_benchmark_suite_resources/scenes/bbt/panda/primitive.urdf.xacro
    # - name: mesh
    #   resource: package://moveit_benchmark_suite_resources/scenes/bbt/panda/mesh_16k.urdf.xacro

  collision_detectors:
    - FCL
    - Bullet

  # Resource moveit_config (planning pipeline)
  # - Override the 'requests' pipeline_id field
  # - Extends query 'planners' which overrides the 'requests' planner_id field
  planning_pipelines:
    - name: ompl
      resource: package://moveit_benchmark_suite_resources/robots/panda/config/ompl_planning.yaml
      parameters:
        planners:
          - RRT
          - RRTConnect
          - EST
          - PRM
          - LBKPIECE
          - BiEST
    # - name: chomp
    #   resource: package://moveit_benchmark_suite_resources/robots/panda/config/chomp_planning.yaml
    #   parameters:
    #     planners:
    #       - CHOMP
