# This is an example configuration that loads the "Kitchen" scene from the
# local MoveIt warehouse and benchmarks the "manipulator" group over all pairs
# of motion plan queries and start states in the Kitchen scene.

# Five planners from two different plugins are run a total of 50 times each, with a
# maximum of 10 seconds per run.  Output is stored in the /tmp/moveit_benchmarks directory.

benchmark_config:
    warehouse:
        host: 127.0.0.1
        port: 33829
        scene_name: bbt_primitive     # Required
    parameters:
        name: bbt_primitive_scene
        runs: 50
        group: panda_arm      # Required
        timeout: 30.0
        output_directory: "/tmp/benchmarks"
        predefined_poses_group: panda_arm # Group where the predefined poses are specified
        predefined_poses: # List of named targets
            - ready
            - extended
        #queries: pick1
        #start_states: start1
    planning_pipelines:
        - name: ompl
          planners:
            #- SBLkConfigDefault
            #- ESTkConfigDefault
            #- LBKPIECEkConfigDefault
            #- BKPIECEkConfigDefault
            #- KPIECEkConfigDefault
            #- RRTkConfigDefault
            - RRTConnectkConfigDefault
            ##- RRTstarkConfigDefault
            ##- TRRTkConfigDefault
            #- PRMkConfigDefault
            ##- PRMstarkConfigDefault
            #- FMTkConfigDefault
            #- BFMTkConfigDefault
            #- PDSTkConfigDefault
            #- STRIDEkConfigDefault
            ##- BiTRRTkConfigDefault
            ##- LBTRRTkConfigDefault
            #- BiESTkConfigDefault
            #- ProjESTkConfigDefault
        #- name: chomp
        #  planners:
        #    - CHOMP
        - name: stomp
          planners:
            - STOMP
