#################################################
# moveit_config planning pieline
#################################################

# Plugin name for MoveIt
planning_plugin: lerp_interface/LERPPlanner

# The request adapters (plugins) used when planning with OMPL.
# ORDER MATTERS
request_adapters: >-
  default_planner_request_adapters/AddTimeParameterization
  default_planner_request_adapters/ResolveConstraintFrames
  default_planner_request_adapters/FixWorkspaceBounds
  default_planner_request_adapters/FixStartStateBounds
  default_planner_request_adapters/FixStartStateCollision
  default_planner_request_adapters/FixStartStatePathConstraints

# FixStartStateBounds parameters
start_state_max_bounds_error: 0.1

# Add MoveGroup capabilities specific to this pipeline
capabilities: ""

#################################################
# lerp planning pipeline
#################################################

num_steps: 40
