<?xml version="1.0" ?>
<robot name="scene" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find urdf_to_scene)/xacro/planning_scene.xacro" />
  <xacro:include filename="$(find moveit_benchmark_suite_resources)/objects/metadata.xacro" />

  <!-- Planning frame -->
  <link name="world"/>
  <planning_fft name="panda_link0"
                parent="world"
                xyz="0.365 0 0"/>

  <!-- World -->
  <xacro:collision_mesh name="boxlid"
                        frame_id="world"
                        xyz="0 ${-boxlid['bb'][2]/2} ${boxlid['bb'][0]/2}"
                        rpy="0 ${pi/2} ${pi/2}"
                        resource="${boxlid.resource}"
                        metadata="${boxlid}"/>

  <xacro:collision_mesh name="clearbox1"
                        frame_id="world"
                        xyz="0 ${-(clearbox['bb'][0]/2 + boxlid['bb'][2]/2)} 0"
                        rpy="0 0 ${pi/2}"
                        resource="${clearbox.resource}"
                        metadata="${clearbox}"/>

  <xacro:collision_mesh name="clearbox2"
                        frame_id="clearbox1"
                        xyz="${clearbox['bb'][0] + boxlid['bb'][2]} 0 0" rpy="0 0 0"
                        resource="${clearbox.resource}"
                        metadata="${clearbox}"/>

  <xacro:macro name="linearpattern" params="current:=0 frame_id:=^ index:=0 until:=^ xyz:=^ rpy=^|'0 0 0' gap:=^">
    <xacro:if value="${until > current}">
      <xacro:collision_mesh name="woodblock${current+index}"
                            frame_id="${frame_id}"
                            xyz="${float(xyz.split()[0]) + current*float(gap.split()[0])}
                                 ${float(xyz.split()[1]) + current*float(gap.split()[1])}
                                 ${float(xyz.split()[2]) + current*float(gap.split()[2])}"
                            rpy="${rpy}"
                            resource="${woodblock.resource}"
                            metadata="${woodblock}"/>
      <xacro:linearpattern current="${current+1}" index="${index}"/>
    </xacro:if>
  </xacro:macro>

  <xacro:property name="stack_z" value="${clearbox['subframes']['stack']['xyz'][2]}"/>

  <xacro:linearpattern index="1"  until="4"  frame_id="clearbox1"  gap="${woodblock['bb'][1]*2} 0 0" xyz="${-3*woodblock['bb'][0]} ${(-3*woodblock['bb'][0])} ${stack_z}" rpy="0 0 ${-pi/2}"/>
  <xacro:linearpattern index="5"  until="4"  frame_id="woodblock1" gap="0 ${woodblock['bb'][1]*2} 0" xyz="${-2*woodblock['bb'][0]} 0 0"/>
  <xacro:linearpattern index="9"  until="4"  frame_id="woodblock5" gap="0 ${woodblock['bb'][1]*2} 0" xyz="${-2*woodblock['bb'][0]} 0 0"/>
  <xacro:linearpattern index="13" until="4"  frame_id="woodblock9" gap="0 ${woodblock['bb'][1]*2} 0" xyz="${-2*woodblock['bb'][0]} 0 0"/>

</robot>
